adverts/urls.py
from django.urls import path

from . import views

app_name = "adverts"

urlpatterns = [
    path("crawl_data/", views.crawl_data, name="crawl_data"),
    path("upload_data/", views.upload_data, name="upload_data"),
    path("plots/", views.plot_search, name="plot_search"),
    path("plot/<int:plot_id>/", views.plot_detail, name="plot_detail"),
    path("saved/", views.saved_adverts, name="saved_adverts"),
    path("saved/plots/", views.saved_plots_list, name="saved_plots"),
    path(
        "save/", views.advert_save, name="save"
    ),
    path(
        "save_all/<str:advert_type>/", views.save_all_adverts, name="save_all_adverts"
    ),
    path(
        "delete_all/<str:advert_type>/<str:section>/",
        views.delete_all_adverts,
        name="delete_all_adverts",
    ),
    path(
        "download_csv/<str:advert_type>/<str:section>",
        views.download_csv,
        name="download_csv",
    ),
    path(
        "send_csv/<str:advert_type>/<str:section>",
        views.sending_csv,
        name="send_csv",
    ),
]

adverts_collector/urls.py
from account.views import dashboard
from django.contrib import admin
from django.urls import path, include

handler404 = "errors.views.error_404"
handler500 = "errors.views.error_500"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("adverts/", include("adverts.urls", namespace="adverts")),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path("upload_data", views.upload_data, name="upload_data"),
    path("", views.plot_search, name="plot_search"),
    path("<int:plot_id>", views.plot_detail, name="plot_detail"),
]

adverts/models.py
import glob
import logging
import os
from typing import *

import pandas as pd
from django.conf import settings
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.db import models, transaction
from django.db.utils import ProgrammingError
from django.urls import reverse


class PlotManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super(PlotManager, self).get_queryset()

    def filter_plots(
        self,
        place: str = None,
        price: int = None,
        area: int = None,
        query: str = None,
        user=None,
    ) -> models.QuerySet:
        """ Returns objects filtered by place, maximum price and minimum area ordered by price. """

        plots = self.get_queryset()
        if user:
            plots = plots.filter(users_save=user)
        if place and place != "None":
            plots = plots.filter(place=place).order_by("price")
        if price and price != 0 and price != "None":
            plots = plots.filter(price__lte=price).order_by("price")
        if area and area != 0 and area != "None":
            plots = plots.filter(area__gte=area).order_by("price")
        plots = self.search_by_description(plots, query)
        return plots

    @staticmethod
    def search_by_description(
        objects: models.QuerySet, search_text: str
    ) -> models.QuerySet:
        if search_text and search_text != "None":
            vector = SearchVector("description")
            query = SearchQuery(search_text)
            objects = (
                objects.annotate(search=vector, rank=SearchRank(vector, query))
                .filter(search=search_text)
                .order_by("-rank")
            )
        return objects


class Plot(models.Model):
    """ Stores scraped building plots data. """

    place = models.CharField(max_length=100, null=True)
    county = models.CharField(max_length=100, null=True)
    price = models.FloatField(null=True)
    price_per_m2 = models.FloatField(null=True)
    area = models.FloatField(null=True)
    link = models.CharField(max_length=500, null=True)
    date_added = models.CharField(max_length=25, null=True)
    description = models.TextField(null=True)
    image_url = models.CharField(max_length=500, null=True)
    objects = models.Manager()
    manager = PlotManager()
    users_save = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="saved_plots", blank=True
    )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("price",)

    def __str__(self):
        return self.place

    def get_absolute_url(self):
        return reverse("adverts:plot_detail", args=[self.id])

    @classmethod
    def create_from_csv(cls, item: list) -> None:
        """ Creates an Advert instance. """
        try:
            with transaction.atomic():
                cls(
                    place=item[0],
                    county=item[1],
                    price=item[2],
                    price_per_m2=item[3],
                    area=item[4],
                    link=item[5],
                    date_added=item[6],
                    description=item[7],
                    image_url=item[8],
                ).save()
        except ValueError as e:
            logging.error(e)

    @classmethod
    def load_adverts(cls, catalog: str) -> None:
        """
        Loads data from files and saves to the database.

        :param catalog: Catalog name with files to be added.
        """

        path = os.path.join(catalog, "*.csv")
        files = glob.glob(path)

        if files:
            for file in files:
                adv = pd.read_csv(file)
                try:
                    for item in adv.values:
                        cls.create_from_csv(item)
                except ProgrammingError:
                    raise ProgrammingError(
                        "You have to make migrations before add data to database."
                    )
        else:
            raise FileNotFoundError("No files to added.")
        logging.info("Data successfully updated.")

    @classmethod
    def delete_duplicates(cls) -> None:
        """ Deletes duplicate objects from the database. """

        min_id_objects = cls.objects.values(
            "place", "price", "price_per_m2", "area"
        ).annotate(minid=models.Min("id"))
        min_ids = [obj["minid"] for obj in min_id_objects]

        cls.objects.exclude(id__in=min_ids).delete()

        logging.info(
            "Amount of adverts after deleting duplicates: {}".format(
                len(cls.objects.all())
            )
        )

    @classmethod
    def get_places(cls, objects: models.QuerySet = None) -> Tuple:
        if objects is None:
            objects = cls.objects.all()
        return tuple(
            set(objects.only("place").values_list("place", flat=True).order_by("place"))
        )

adverts/forms.py
from django import forms

from .fields import ListTextWidget
from .validators import validate_positive


class SearchPlotForm(forms.Form):
    place = forms.CharField(
        max_length=250,
        label="Miejscowość",
        help_text="Podaj lokalizację działki - pole wymagane",
        required=True,
    )
    price = forms.IntegerField(
        label="Cena",
        help_text="Podaj maksymalną cenę - pole opcjonalne",
        required=False,
        validators=[validate_positive],
    )
    area = forms.IntegerField(
        label="Powierzchnia",
        help_text="Podaj minimalną powierzchnię w metrach kwadratowych - pole opcjonalne",
        required=False,
        validators=[validate_positive],
    )
    query = forms.CharField(
        label="Wyszukaj w opisie",
        help_text="Wpisz frazę, którą chcesz wyszukać w opisie - pole opcjonalne",
        required=False,
    )

    def __init__(self, *args, **kwargs):
        _data_list = kwargs.pop("data_list", None)
        _place_not_required = kwargs.pop("place_not_required", None)
        super().__init__(*args, **kwargs)
        if _place_not_required:
            self.fields["place"].required = False
            self.fields[
                "place"
            ].help_text = "Podaj lokalizację działki - pole opcjonalne"
        self.fields["place"].widget = ListTextWidget(
            data_list=_data_list, name="place-list"
        )

    def clean(self):
        data = super().clean()
        for key, val in data.items():
            if val == "":
                data[key] = "None"
            elif val is None:
                data[key] = 0
        return data

adverts/views.py
import csv
from io import StringIO

from common.decorators import ajax_required
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, StreamingHttpResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.views.decorators.http import require_POST

from . import tasks, uploads
from .forms import SearchPlotForm
from .helpers import Echo, get_adverts, prepare_plot_to_csv
from .models import Plot
from .pagination import paginate


def crawl_data(request):
    uploads.run_spider.delay()
    return JsonResponse({"OK": "Crawling data started."})


def upload_data(request):
    uploads.upload_plots.delay()
    return JsonResponse({"OK": "Uploading data started."})


def plot_search(request):
    plots = []
    place = request.GET.get("place")
    price = request.GET.get("price")
    area = request.GET.get("area")
    query = request.GET.get("query")
    page = request.GET.get("page")
    form = SearchPlotForm(data_list=Plot.get_places())
    if place:
        form = SearchPlotForm(request.GET, data_list=Plot.get_places())
        if form.is_valid():
            data = form.cleaned_data
            place = data.get("place")
            price = data.get("price")
            area = data.get("area")
            query = data.get("query")
        object_list = Plot.manager.filter_plots(place, price, area, query)
        plots = paginate(object_list, page, 6)
    return render(
        request,
        "adverts/plot/search.html",
        {
            "form": form,
            "place": place,
            "price": price,
            "area": area,
            "query": query,
            "page": page,
            "plots": plots,
            "section": "search",
        },
    )


def plot_detail(request, plot_id: int):
    plot = get_object_or_404(Plot, id=plot_id)
    return render(request, "adverts/plot/detail.html", {"plot": plot})


@login_required
def saved_adverts(request):
    return render(request, "adverts/adverts/saved.html")


@login_required
def saved_plots_list(request):
    place = request.GET.get("place")
    price = request.GET.get("price")
    area = request.GET.get("area")
    query = request.GET.get("query")
    page = request.GET.get("page")
    form = SearchPlotForm(
        request.GET,
        data_list=Plot.get_places(request.user.saved_plots),
        place_not_required=True,
    )
    if form.is_valid():
        data = form.cleaned_data
        place = data.get("place")
        price = data.get("price")
        area = data.get("area")
        query = data.get("query")
    object_list = Plot.manager.filter_plots(
        place, price, area, query, user=request.user
    )
    plots = paginate(object_list, page, 6)
    return render(
        request,
        "adverts/plot/saved.html",
        {
            "form": form,
            "place": place,
            "price": price,
            "area": area,
            "query": query,
            "page": page,
            "plots": plots,
            "section": "saved",
        },
    )


@ajax_required
@login_required
@require_POST
def advert_save(request):
    advert_type = request.POST.get("type")
    advert_id = request.POST.get("id")
    action = request.POST.get("action")
    if advert_id and action:
        if advert_type == "plot":
            try:
                plot = Plot.objects.get(id=advert_id)
            except Plot.DoesNotExist:
                pass
            else:
                if action == "save":
                    request.user.saved_plots.add(plot)
                else:
                    request.user.saved_plots.remove(plot)
                request.user.save()
                return JsonResponse({"status": "ok"})
    return JsonResponse({"status": "error"})


@login_required
def save_all_adverts(request, advert_type: str):
    adverts = get_adverts(request, advert_type)
    for advert in adverts:
        request.user.saved_plots.add(advert)
    messages.success(request, "Pomyślnie zapisano wszystkie ogłoszenia.")
    return redirect(request.META["HTTP_REFERER"])


@login_required
def delete_all_adverts(request, advert_type: str, section: str = None):
    adverts = get_adverts(request, advert_type, user=request.user)
    for advert in adverts:
        request.user.saved_plots.remove(advert)
    messages.success(request, "Pomyślnie usunięto wszystkie ogłoszenia.")
    if section == "saved":
        return redirect(reverse("adverts:saved_plots"))
    return redirect(request.META["HTTP_REFERER"])


def download_csv(request, advert_type: str, section: str = None):
    user = None
    if section == "saved":
        user = request.user
    adverts = get_adverts(request, advert_type, user)
    rows = prepare_plot_to_csv(adverts)
    pseudo_buffer = Echo()
    writer = csv.writer(pseudo_buffer)
    response = StreamingHttpResponse(
        (writer.writerow(row) for row in rows), content_type="text/csv"
    )
    response["Content-Disposition"] = 'attachment; filename="your_adverts.csv"'
    return response


def sending_csv(request, advert_type: str, section: str = None):
    user = None
    if section == "saved":
        user = request.user
    adverts = get_adverts(request, advert_type, user)
    rows = prepare_plot_to_csv(adverts)
    csv_file = StringIO()
    writer = csv.writer(csv_file)
    [writer.writerow(row) for row in rows]
    recipient = request.user.email
    tasks.send_email.delay(
        subject="ParcelsScraper - wybrane działki",
        body="W załączeniu przesyłamy wybrane przez Ciebie działki.",
        to=[recipient],
        attachments=[("your_adverts.csv", csv_file.getvalue(), "text/csv")],
    )
    messages.success(
        request,
        "Wybrane działki zostały wysłane na adres email podany przy rejestracji.",
    )
    return redirect(request.META["HTTP_REFERER"])

adverts/templates/adverts/plot/detail.html
{% extends "base.html" %}
{% load adverts_tags %}

{% block title %}Szczegóły{% endblock %}

{% block content %}

<main>
  {% with user_saved_plots=request.user.saved_plots.all %}
	<div class="col">
	  <div class="card shadow-sm">
		<svg class="bd-placeholder-img card-img-top" width="200%" height="450" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="200%" height="200%" fill="#55595c"/><image href="{{ plot.image_url }}" height="100%" width="100%"/></svg>

		<div class="card-body">
		  <div class="d-flex justify-content-between align-items-center">
			<div class="btn-group">
			  <button type="button" class="btn btn-sm btn-outline-secondary">
				  {% if request.GET.section == 'saved' %}
  				    <a class="btn btn-sm" href="{% url 'adverts:saved_plots' %}?{% query_transform %}">Powrót</a>
				  {% elif request.GET.section == 'search' %}
  				    <a class="btn btn-sm" href="{% url 'adverts:plot_search' %}?{% query_transform %}">Powrót</a>
				  {% else %}
  				    <a class="btn btn-sm" href="{% url 'dashboard' %}">Powrót</a>
				  {% endif %}
			  </button>

              {% if request.user.is_authenticated %}
			    {% include "adverts/adverts/advert_save_button.html" with advert_type='plot' user_saved_adverts=user_saved_plots advert=plot %}
              {% endif %}
  
			</div>
		  </div><br>
			<h4  class="card-text">{{ plot.place }}</h4>
			<h5  class="card-text">{% if plot.county != 'brak danych' %}powiat {{ plot.county }}{% endif %}</h5>
			<table>
				<tr>
					<td><p class="card-text">Cena</p></td>
					<td><h5 class="card-text">{{ plot.price }} PLN</h5></td>
				</tr>
				<tr>
					<td><p class="card-text">Powierzchnia</p></td>
					<td><h5 class="card-text">{{ plot.area }} m2</h5></td>
				</tr>
				<tr>
					<td><p class="card-text">Cena za m2</p></td>
					<td><h5 class="card-text">{{ plot.price_per_m2 }} PLN/m2</h5></td>
				</tr>
			</table><br>
		  <p class="card-text">{{ plot.description }}</p>
		  <p class="card-text">Dodano: {{ plot.date_added }}</p>
		  <p class="card-text"><a href="{{ plot.link }}">Link do ogłoszenia</a></p>
		</div>
	  </div>
	</div>
  {% endwith %}
</main>
{% endblock %}

{% block domready %}
  $('a.save').click(function(e){
    e.preventDefault();
    advert_id = $(this).data('id');
    $.post('{% url "adverts:save" %}',
      {
        id: $(this).data('id'),
        type: $(this).data('type'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('[id=' + advert_id + ']').data('action');

          // toggle data-action
          $('[id=' + advert_id + ']').data('action', previous_action == 'save' ? 'remove' : 'save');

          // toggle link text
          $('[id=' + advert_id + ']').text(previous_action == 'save' ? 'Usuń' : 'Zapisz');
        }
      }
    );
  });
{% endblock %}

adverts/templates/adverts/plot/list.html
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
  {% for plot in plots %}
  <div class="col">
    <div class="card shadow-sm">
      <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><image href="{{ plot.image_url }}" height="100%" width="100%"/></svg>

      <div class="card-body">
        <h5  class="card-text">{{ plot.place }}</h5>
        <h6  class="card-text">{% if plot.county != 'brak danych' %}powiat {{ plot.county }}{% endif %}</h6>
        <h6  class="card-text">{{ plot.price }} PLN</h6>
        <h6  class="card-text">{{ plot.area }} m2</h6>
        <h6  class="card-text">{{ plot.price_per_m2 }} PLN/m2</h6>
        <p class="card-text" style="display: -webkit-box; -webkit-line-clamp: 4; -webkit-box-orient: vertical; overflow: hidden;">{{ plot.description }}</p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group btn-group-sm">
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <a class="btn btn-sm" href="{{ plot.get_absolute_url }}">Wyświetl</a>
            </button>
          </div>
          <small class="text-muted">{{ plot.date_added }}</small>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

adverts/templates/adverts/plot/list_with_buttons.html
{% load adverts_tags %}

<div class="d-flex justify-content-center pb-3">
  <div class="btn-group btn-group-sm">
    {% if plots %}
      {% if user.is_authenticated %}
        {% if section != 'saved' %}
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a class="btn btn-sm" href="{% url 'adverts:save_all_adverts' advert_type='plot' %}?{% query_transform %}">Zapisz wyfiltrowane</a>
        </button>
        {% endif %}
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a class="btn btn-sm" href="{% url 'adverts:delete_all_adverts' advert_type='plot' section=section %}?{% query_transform %}">Usuń wyfiltrowane</a>
        </button>
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a class="btn btn-sm" href="{% url 'adverts:download_csv' advert_type='plot' section=section %}?{% query_transform %}">Pobierz jako plik csv</a>
        </button>
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a class="btn btn-sm" href="{% url 'adverts:send_csv' advert_type='plot' section=section %}?{% query_transform %}">Wyślij email z plikiem csv</a>
        </button>
      {% else %}
        <p>Zaloguj się, aby usyskać więcej opcji.</p>
      {% endif %}
    {% endif %}
  </div>
</div>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
  {% with user_saved_plots=request.user.saved_plots.all %}
    {% for plot in plots %}
    <div class="col">
      <div class="card shadow-sm">
        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><image href="{{ plot.image_url }}" height="100%" width="100%"/></svg>

        <div class="card-body">
          <h5  class="card-text">{{ plot.place }}</h5>
          <h6  class="card-text">{% if plot.county != 'brak danych' %}powiat {{ plot.county }}{% endif %}</h6>
          <h6  class="card-text">{{ plot.price }} PLN</h6>
          <h6  class="card-text">{{ plot.area }} m2</h6>
          <h6  class="card-text">{{ plot.price_per_m2 }} PLN/m2</h6>
          <p class="card-text" style="display: -webkit-box; -webkit-line-clamp: 4; -webkit-box-orient: vertical; overflow: hidden;">{{ plot.description }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group btn-group-sm">
              <button type="button" class="btn btn-sm btn-outline-secondary">
                <a class="btn btn-sm" href="{{ plot.get_absolute_url }}?{% query_transform section=section %}">Wyświetl</a>
              </button>

              {% if request.user.is_authenticated %}
                {% include "adverts/adverts/advert_save_button.html" with advert_type='plot' user_saved_adverts=user_saved_plots advert=plot %}
              {% endif %}
              
            </div>
            <small class="text-muted">{{ plot.date_added }}</small>
          </div>
        </div>
      </div>
    </div>
    {% empty %}
      <div class="container pt-5">
          <p class="text-center">Brak wyników do wyświetlenia.</p>
      </div>
    {% endfor %}
  {% endwith %}
</div>

adverts/templates/adverts/plot/plots.html
{% load adverts_tags %}

<div class="d-flex justify-content-center pb-3">
  <div class="btn-group btn-group-sm">
    {% if plots %}
      {% if user.is_authenticated %}
        {% if section != 'saved' %}
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a class="btn btn-sm" href="{% url 'adverts:save_all_adverts' advert_type='plot' %}?{% query_transform %}">Zapisz wszystkie</a>
        </button>
        {% endif %}
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a class="btn btn-sm" href="{% url 'adverts:delete_all_adverts' advert_type='plot' section=section %}?{% query_transform %}">Usuń wszystkie</a>
        </button>
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a class="btn btn-sm" href="{% url 'adverts:download_csv' advert_type='plot' section=section %}?{% query_transform %}">Pobierz jako plik csv</a>
        </button>
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <a class="btn btn-sm" href="{% url 'adverts:send_csv' advert_type='plot' section=section %}?{% query_transform %}">Wyślij email z plikiem csv</a>
        </button>
      {% else %}
        <p>Zaloguj się, aby usyskać więcej opcji.</p>
      {% endif %}
    {% endif %}
  </div>
</div>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
  {% for plot in plots %}
  <div class="col">
    <div class="card shadow-sm">
      <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><image href="{{ plot.image_url }}" height="100%" width="100%"/></svg>

      <div class="card-body">
        <h5  class="card-text">{{ plot.place }}</h5>
        <h6  class="card-text">{% if plot.county != 'brak danych' %}powiat {{ plot.county }}{% endif %}</h6>
        <h6  class="card-text">{{ plot.price }} PLN</h6>
        <h6  class="card-text">{{ plot.area }} m2</h6>
        <h6  class="card-text">{{ plot.price_per_m2 }} PLN/m2</h6>
        <p class="card-text" style="display: -webkit-box; -webkit-line-clamp: 4; -webkit-box-orient: vertical; overflow: hidden;">{{ plot.description }}</p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group btn-group-sm">
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <a class="btn btn-sm" href="{{ plot.get_absolute_url }}?{% query_transform section=section %}">Wyświetl</a>
            </button>
            {% if user.is_authenticated %}
                <button type="button" class="btn btn-sm btn-outline-secondary" onclick="saveScrollPos()">
                  {% if plot in user.saved_plots.all %}
                    <a class="btn btn-sm" href="{% url 'adverts:delete_advert' advert_type='plot' advert_id=plot.id %}">Usuń</a>
                  {% else %}
                    <a class="btn btn-sm" href="{% url 'adverts:save_advert' advert_type='plot' advert_id=plot.id %}">Zapisz</a>
                  {% endif %}
                </button>
            {% endif %}
          </div>
          <small class="text-muted">{{ plot.date_added }}</small>
        </div>
      </div>
    </div>
  </div>
  {% empty %}
    <div class="container pt-5">
        <p class="text-center">Brak wyników wyszukiwania. Spróbuj wprowadzić inne dane.</p>
    </div>
  {% endfor %}
</div>

adverts/templates/adverts/plot/saved.html
{% extends "base.html" %}

{% block title %}Działki budowlane{% endblock %}

{% block content %}
  <div class="row">
    <div class="col">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="container">
                    {% include "adverts/plot/search_form.html" with form=form %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-9">
        {% include "adverts/plot/list_with_buttons.html" with plots=plots %}

        {% if plots %}
        <div class="container pt-3">
          <div class="d-flex justify-content-center">
              {% include "pagination.html" with page=plots %}
          </div>
        </div>
        {% endif %}

    </div>
 </div>

{% endblock %}

{% block domready %}
  $('a.save').click(function(e){
    e.preventDefault();
    advert_id = $(this).data('id');
    $.post('{% url "adverts:save" %}',
      {
        id: $(this).data('id'),
        type: $(this).data('type'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          // delete card from list
          $('[id=' + advert_id + ']').parent().parent().parent().parent().parent().remove();
        }
      }
    );
  });
{% endblock %}

adverts/templates/adverts/plot/search.html
{% extends "base.html" %}

{% block title %}Działki budowlane{% endblock %}

{% block content %}
  <div class="row">
    <div class="col">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="container">
                    {% include "adverts/plot/search_form.html" with form=form %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-9">
        {% if place %}
            {% include "adverts/plot/list_with_buttons.html" with plots=plots %}
        {% else %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="container pt-5">
              <p class="text-center">Wprowadź dane i kliknij szukaj, aby wyświetlić wyniki.</p>
            </div>
        {% endif %}
        </div>

        {% if plots %}
        <div class="container pt-3">
          <div class="d-flex justify-content-center">
              {% include "pagination.html" with page=plots %}
          </div>
        </div>
        {% endif %}

    </div>
 </div>

{% endblock %}

{% block domready %}
  $('a.save').click(function(e){
    e.preventDefault();
    advert_id = $(this).data('id');
    $.post('{% url "adverts:save" %}',
      {
        id: $(this).data('id'),
        type: $(this).data('type'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('[id=' + advert_id + ']').data('action');

          // toggle data-action
          $('[id=' + advert_id + ']').data('action', previous_action == 'save' ? 'remove' : 'save');

          // toggle link text
          $('[id=' + advert_id + ']').text(previous_action == 'save' ? 'Usuń' : 'Zapisz');
        }
      }
    );
  });
{% endblock %}

adverts/templates/adverts/plot/search_form.html
{% load crispy_forms_tags %}

<h4 class="text-center">Wyszukaj:</h4>
<form method="get" novalidate>
    {{ form|crispy }}
    <br>
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-success">Szukaj</button>
    </div>
    <br>
    <p class="text-center"><a href="{{ request.path }}">Usuń filtry</a></p>

</form>