account/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
    path("edit/", views.edit, name="edit"),
]

adverts/urls.py
from django.urls import path

from . import views

app_name = "adverts"

urlpatterns = [
    path("crawl_data/", views.crawl_data, name="crawl_data"),
    path("upload_data/", views.upload_data, name="upload_data"),
    path("plots/", views.plot_search, name="plot_search"),
    path("plot/<int:plot_id>/", views.plot_detail, name="plot_detail"),
    path("saved/", views.saved_adverts, name="saved_adverts"),
    path("saved/plots/", views.saved_plots_list, name="saved_plots"),
    path(
        "save/", views.advert_save, name="save"
    ),
    path(
        "save_all/<str:advert_type>/", views.save_all_adverts, name="save_all_adverts"
    ),
    path(
        "delete_all/<str:advert_type>/<str:section>/",
        views.delete_all_adverts,
        name="delete_all_adverts",
    ),
    path(
        "download_csv/<str:advert_type>/<str:section>",
        views.download_csv,
        name="download_csv",
    ),
    path(
        "send_csv/<str:advert_type>/<str:section>",
        views.sending_csv,
        name="send_csv",
    ),
]

adverts_collector/urls.py
from account.views import dashboard
from django.contrib import admin
from django.urls import path, include

handler404 = "errors.views.error_404"
handler500 = "errors.views.error_500"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("adverts/", include("adverts.urls", namespace="adverts")),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path("upload_data", views.upload_data, name="upload_data"),
    path("", views.plot_search, name="plot_search"),
    path("<int:plot_id>", views.plot_detail, name="plot_detail"),
]

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    date_of_birth = models.DateField(blank=True, null=True)

account/forms.py
from django import forms

from .models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Hasło", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Powtórz hasło", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "first_name", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("Passwords don't match.")
        return cd["password2"]


class UserEditForm(forms.ModelForm):
    date_of_birth = forms.DateField(label="Data urodzin", required=False)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")

account/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse

from .forms import UserRegistrationForm, UserEditForm


def dashboard(request):
    return render(request, "account/dashboard.html")


def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()
            return HttpResponseRedirect(reverse("login"))
    user_form = UserRegistrationForm()
    return render(request, "account/register.html", {"user_form": user_form})


@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, "Profil został pomyślnie zmieniony")
        else:
            messages.error(request, "Wystąpił błąd podczas edycji profilu")
    else:
        user_form = UserEditForm(instance=request.user)
    return render(request, "account/edit.html", {"user_form": user_form})

account/templates/base.html
<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
    {% load static %}
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">

  </head>
  <body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'dashboard' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'adverts:saved_adverts' %}">Zapisane</a>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav ml-auto mb-2 mb-md-0">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" aria-current="page">Witaj: {{ user.username }}</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'edit' %}">Profil</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'logout' %}">Wyloguj</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'register' %}">Zarejestruj</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" aria-current="page" href="{% url 'login' %}">Zaloguj</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<main class="container">

  <div class="starter-template text-center py-5 px-3">
    <h1>Adverts Collector</h1>
    <p class="lead">Aplikacja zbierająca ogłoszenia z różnych serwisów w jedno miejsce</p>
  </div>

  <div class="container pb-5">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">{{ message|safe }}</div>
        {% endfor %}
    {% endif %}
  </div>

  {% block content %}
  {% endblock %}

  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
      <p class="mb-1">Created by konradkrasno</p>
      <p class="mb-0">To see more projects, visit my <a href="https://github.com/konradkrasno">GitHub</a> page.</p>
    </div>
  </footer>
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
<script>
  var csrftoken = Cookies.get('csrftoken');
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });
  $(document).ready(function(){
    {% block domready %}
    {% endblock %}
  });
</script>

</body>
</html>