adverts_collector/urls.py
from account.views import dashboard
from django.contrib import admin
from django.urls import path, include

handler404 = "errors.views.error_404"
handler500 = "errors.views.error_500"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("adverts/", include("adverts.urls", namespace="adverts")),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path("upload_data", views.upload_data, name="upload_data"),
    path("", views.plot_search, name="plot_search"),
    path("<int:plot_id>", views.plot_detail, name="plot_detail"),
]

store/models.py
import glob
import logging
import os
from typing import *

import pandas as pd
from django.contrib.auth.models import User
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.db import models, transaction
from django.db.utils import ProgrammingError
from django.urls import reverse
from django.conf import settings


class PlotManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super(PlotManager, self).get_queryset()

    def filter_plots(
        self, place: str = None, price: int = None, area: int = None, query: str = None
    ) -> models.QuerySet:
        """ Returns objects filtered by place, maximum price and minimum area ordered by price. """

        plots = self.get_queryset()
        if place and place != "None":
            plots = plots.filter(place=place).order_by("price")
        if price and price != 0 and price != "None":
            plots = plots.filter(price__lte=price).order_by("price")
        if area and area != 0 and area != "None":
            plots = plots.filter(area__gte=area).order_by("price")
        plots = self.search_by_description(plots, query)
        return plots

    @staticmethod
    def search_by_description(
        objects: models.QuerySet, search_text: str
    ) -> models.QuerySet:
        if search_text and search_text != "None":
            vector = SearchVector("description")
            query = SearchQuery(search_text)
            objects = (
                objects.annotate(search=vector, rank=SearchRank(vector, query))
                .filter(search=search_text)
                .order_by("-rank")
            )
        return objects


class Plot(models.Model):
    """ Stores scraped building plots data. """

    place = models.CharField(max_length=100, null=True)
    county = models.CharField(max_length=100, null=True)
    price = models.FloatField(null=True)
    price_per_m2 = models.FloatField(null=True)
    area = models.FloatField(null=True)
    link = models.CharField(max_length=500, null=True)
    date_added = models.CharField(max_length=25, null=True)
    description = models.TextField(null=True)
    image_url = models.CharField(max_length=500, null=True)
    objects = models.Manager()
    manager = PlotManager()

    class Meta:
        ordering = ("price",)

    def __str__(self):
        return self.place

    def get_absolute_url(self):
        return reverse("store:plot_detail", args=[self.id])

    @classmethod
    def create_from_csv(cls, item: list) -> None:
        """ Creates an Advert instance. """
        try:
            with transaction.atomic():
                cls(
                    place=item[0],
                    county=item[1],
                    price=item[2],
                    price_per_m2=item[3],
                    area=item[4],
                    link=item[5],
                    date_added=item[6],
                    description=item[7],
                    image_url=item[8],
                ).save()
        except ValueError as e:
            logging.error(e)

    @classmethod
    def load_adverts(cls, catalog: str) -> None:
        """
        Loads data from files and saves to the database.

        :param catalog: Catalog name with files to be added.
        """

        path = os.path.join(catalog, "*.csv")
        files = glob.glob(path)

        if files:
            for file in files:
                adv = pd.read_csv(file)
                try:
                    for item in adv.values:
                        cls.create_from_csv(item)
                except ProgrammingError:
                    raise ProgrammingError(
                        "You have to make migrations before add data to database."
                    )
        else:
            raise FileNotFoundError("No files to added.")
        logging.info("Data successfully updated.")

    @classmethod
    def delete_duplicates(cls) -> None:
        """ Deletes duplicate objects from the database. """

        min_id_objects = cls.objects.values(
            "place", "price", "price_per_m2", "area"
        ).annotate(minid=models.Min("id"))
        min_ids = [obj["minid"] for obj in min_id_objects]

        cls.objects.exclude(id__in=min_ids).delete()

        logging.info(
            "Amount of adverts after deleting duplicates: {}".format(
                len(cls.objects.all())
            )
        )

    @classmethod
    def get_places(cls) -> Tuple:
        return tuple(
            set(
                cls.objects.only("place")
                .values_list("place", flat=True)
                .order_by("place")
            )
        )


class SavedAdverts(models.Model):
    """ Creates relationships between the user and its saved adverts.  """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="saved_adverts"
    )
    plots = models.ManyToManyField(Plot)

store/views.py
import logging

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

from .forms import SearchPlotForm
from .models import Plot
from .pagination import paginate
from .uploads import upload_plots


def upload_data(request):
    upload_plots()
    logging.info("Data successfully updated.")
    return JsonResponse({"OK": "Uploading data task pushed."})


def plot_search(request):
    plots = []
    place = request.GET.get("place")
    price = request.GET.get("price")
    area = request.GET.get("area")
    query = request.GET.get("query")
    page = request.GET.get("page")
    form = SearchPlotForm(data_list=Plot.get_places())
    if place:
        form = SearchPlotForm(request.GET, data_list=Plot.get_places())
        if form.is_valid():
            data = form.cleaned_data
            place = data.get("place")
            price = data.get("price")
            area = data.get("area")
            query = data.get("query")
        object_list = Plot.manager.filter_plots(place, price, area, query)
        plots = paginate(object_list, page, 6)
    return render(
        request,
        "store/plot/search.html",
        {
            "form": form,
            "place": place,
            "price": price,
            "area": area,
            "query": query,
            "page": page,
            "plots": plots,
        },
    )


def plot_detail(request, plot_id: int):
    plot = get_object_or_404(Plot, id=plot_id)
    return render(
        request, "store/plot/detail.html", {"plot": plot}
    )


def saved_plots_list(request):
    pass

store/templates/store/plot/detail.html
{% extends "base.html" %}
{% load store_tags %}

{% block title %}Szczegóły{% endblock %}

{% block content %}

<main>
	<div class="col">
	  <div class="card shadow-sm">
		<svg class="bd-placeholder-img card-img-top" width="200%" height="450" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="200%" height="200%" fill="#55595c"/><image href="{{ plot.image_url }}" height="100%" width="100%"/></svg>

		<div class="card-body">
		  <div class="d-flex justify-content-between align-items-center">
			<div class="btn-group">
			  <button type="button" class="btn btn-sm btn-outline-secondary">
				<a class="btn btn-sm" href="{% url 'store:plot_search' %}?{% query_transform %}">Powrót</a>
			  </button>
			  {% if user.is_authenticated %}
			    <button type="button" class="btn btn-sm btn-outline-secondary">
				   <a class="btn btn-sm" href="#">Zapisz</a>
			    </button>
			  {% endif %}
        </div>
		  </div><br>
			<h4  class="card-text">{{ plot.place }}</h4>
			<h5  class="card-text">{% if plot.county != 'brak danych' %}powiat {{ plot.county }}{% endif %}</h5>
			<table>
				<tr>
					<td><p class="card-text">Cena</p></td>
					<td><h5 class="card-text">{{ plot.price }} PLN</h5></td>
				</tr>
				<tr>
					<td><p class="card-text">Powierzchnia</p></td>
					<td><h5 class="card-text">{{ plot.area }} m2</h5></td>
				</tr>
				<tr>
					<td><p class="card-text">Cena za m2</p></td>
					<td><h5 class="card-text">{{ plot.price_per_m2 }} PLN/m2</h5></td>
				</tr>
			</table><br>
		  <p class="card-text">{{ plot.description }}</p>
		  <p class="card-text">Dodano: {{ plot.date_added }}</p>
		  <p class="card-text"><a href="{{ plot.link }}">Link do ogłoszenia</a></p>
		</div>
	  </div>
	</div>
</main>

{% endblock %}

store/templates/store/plot/list.html
{% extends "base.html" %}

{% block title %}Działki budowlane{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h5><a href="{% url 'store:plot_search' %}">Wyszukaj ponownie</a></h5><br>
</div>

<div class="album py-5 bg-light">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% include "store/plot/plots.html" with plots=plots %}
    </div>
</div>

{% if plots %}
   {% include "pagination.html" with page=plots %}
{% endif %}

{% endblock %}

store/templates/store/plot/plots.html
{% load store_tags %}

{% for plot in plots %}
<div class="col">
  <div class="card shadow-sm">
    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><image href="{{ plot.image_url }}" height="100%" width="100%"/></svg>

    <div class="card-body">
      <h5  class="card-text">{{ plot.place }}</h5>
      <h6  class="card-text">{% if plot.county != 'brak danych' %}powiat {{ plot.county }}{% endif %}</h6>
      <h6  class="card-text">{{ plot.price }} PLN</h6>
      <h6  class="card-text">{{ plot.area }} m2</h6>
      <h6  class="card-text">{{ plot.price_per_m2 }} PLN/m2</h6>
      <p class="card-text" style="display: -webkit-box; -webkit-line-clamp: 4; -webkit-box-orient: vertical; overflow: hidden;">{{ plot.description }}</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group btn-group-sm">
          <button type="button" class="btn btn-sm btn-outline-secondary">
            <a class="btn btn-sm" href="{{ plot.get_absolute_url }}?{% query_transform %}">Wyświetl</a>
          </button>
          {% if user.is_authenticated %}
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <a class="btn btn-sm" href="#">Zapisz</a>
            </button>
          {% endif %}
        </div>
        <small class="text-muted">{{ plot.date_added }}</small>
      </div>
    </div>
  </div>
</div>
{% empty %}
  <div class="container pt-5">
    <p class="text-center">Brak wyników wyszukiwania. Spróbuj wprowadzić inne dane.</p>
  </div>
{% endfor %}

store/templates/store/plot/search.html
{% extends "base.html" %}

{% block title %}Działki budowlane{% endblock %}

{% block content %}
  <div class="row">
    <div class="col">
        <div class="container">
            <div class="d-flex justify-content-center">
                <div class="container">
                    {% include "store/plot/search_form.html" with form=form %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-9">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% if place %}
            {% include "store/plot/plots.html" with plots=plots %}
        {% else %}
            <div class="container pt-5">
              <p class="text-center">Wprowadź dane i kliknij szukaj, aby wyświetlić wyniki.</p>
            </div>
        {% endif %}
        </div>

        {% if plots %}
        <div class="container pt-3">
          <div class="d-flex justify-content-center">
              {% include "pagination.html" with page=plots %}
          </div>
        </div>
        {% endif %}

    </div>
 </div>

{% endblock %}